// Source: https://en.wikipedia.org/wiki/List_of_sovereign_states

'use strict';

module.exports = [
	['AF', { label: 'Afghanistan' }],
	['AL', { label: 'Albania' }],
	['DZ', { label: 'Algeria' }],
	['AD', { label: 'Andorra' }],
	['AO', { label: 'Angola' }],
	['AI', { label: 'Anguilla' }],
	['AG', { label: 'Antigua and Barbuda' }],
	['AR', { label: 'Argentina' }],
	['AM', { label: 'Armenia' }],
	['AU', { label: 'Australia' }],
	['AT', { label: 'Austria' }],
	['AZ', { label: 'Azerbaijan' }],
	['BS', { label: 'Bahamas' }],
	['BH', { label: 'Bahrain' }],
	['BD', { label: 'Bangladesh' }],
	['BB', { label: 'Barbados' }],
	['BY', { label: 'Belarus' }],
	['BE', { label: 'Belgium' }],
	['BZ', { label: 'Belize' }],
	['BJ', { label: 'Benin' }],
	['BT', { label: 'Bhutan' }],
	['BO', { label: 'Bolivia' }],
	['BA', { label: 'Bosnia and Herzegovina' }],
	['BW', { label: 'Botswana' }],
	['BR', { label: 'Brazil' }],
	['BN', { label: 'Brunei' }],
	['BG', { label: 'Bulgaria' }],
	['BF', { label: 'Burkina Faso' }],
	['MM', { label: 'Burma' }],
	['BI', { label: 'Burundi' }],
	['KH', { label: 'Cambodia' }],
	['CM', { label: 'Cameroon' }],
	['CA', { label: 'Canada' }],
	['CV', { label: 'Cape Verde' }],
	['CF', { label: 'Central African Republic' }],
	['TD', { label: 'Chad' }],
	['CL', { label: 'Chile' }],
	['CN', { label: 'China' }],
	['CO', { label: 'Colombia' }],
	['KM', { label: 'Comoros' }],
	['CD', { label: 'Congo, Democratic Republic' }],
	['CG', { label: 'Congo, Republic' }],
	['CR', { label: 'Costa Rica' }],
	['HR', { label: 'Croatia' }],
	['CU', { label: 'Cuba' }],
	['CY', { label: 'Cyprus' }],
	['CZ', { label: 'Czech Republic' }],
	['DK', { label: 'Denmark' }],
	['DJ', { label: 'Djibouti' }],
	['DM', { label: 'Dominica' }],
	['DO', { label: 'Dominican Republic' }],
	['TL', { label: 'East Timor' }],
	['EC', { label: 'Ecuador' }],
	['EG', { label: 'Egypt' }],
	['SV', { label: 'El Salvador' }],
	['GQ', { label: 'Equatorial Guinea' }],
	['ER', { label: 'Eritrea' }],
	['EE', { label: 'Estonia' }],
	['ET', { label: 'Ethiopia' }],
	['FJ', { label: 'Fiji' }],
	['FI', { label: 'Finland' }],
	['FR', { label: 'France' }],
	['GA', { label: 'Gabon' }],
	['GM', { label: 'Gambia' }],
	['GE', { label: 'Georgia' }],
	['DE', { label: 'Germany' }],
	['GH', { label: 'Ghana' }],
	['GR', { label: 'Greece' }],
	['GD', { label: 'Grenada' }],
	['GT', { label: 'Guatemala' }],
	['GN', { label: 'Guinea' }],
	['GW', { label: 'Guinea-Bissau' }],
	['GY', { label: 'Guyana' }],
	['HT', { label: 'Haiti' }],
	['HN', { label: 'Honduras' }],
	['HU', { label: 'Hungary' }],
	['IS', { label: 'Iceland' }],
	['IN', { label: 'India' }],
	['ID', { label: 'Indonesia' }],
	['IR', { label: 'Iran' }],
	['IQ', { label: 'Iraq' }],
	['IE', { label: 'Ireland' }],
	['IL', { label: 'Israel' }],
	['IT', { label: 'Italy' }],
	['CI', { label: 'Ivory Coast' }],
	['JM', { label: 'Jamaica' }],
	['JP', { label: 'Japan' }],
	['JO', { label: 'Jordan' }],
	['KZ', { label: 'Kazakhstan' }],
	['KE', { label: 'Kenya' }],
	['KI', { label: 'Kiribati' }],
	['KP', { label: 'Korea, North' }],
	['KR', { label: 'Korea, South' }],
	['KW', { label: 'Kuwait' }],
	['KG', { label: 'Kyrgyzstan' }],
	['LA', { label: 'Laos' }],
	['LV', { label: 'Latvia' }],
	['LB', { label: 'Lebanon' }],
	['LS', { label: 'Lesotho' }],
	['LR', { label: 'Liberia' }],
	['LY', { label: 'Libya' }],
	['LI', { label: 'Liechtenstein' }],
	['LT', { label: 'Lithuania' }],
	['LU', { label: 'Luxembourg' }],
	['MK', { label: 'Macedonia' }],
	['MG', { label: 'Madagascar' }],
	['MW', { label: 'Malawi' }],
	['MY', { label: 'Malaysia' }],
	['MV', { label: 'Maldives' }],
	['ML', { label: 'Mali' }],
	['MT', { label: 'Malta' }],
	['MH', { label: 'Marshall Islands' }],
	['MR', { label: 'Mauritania' }],
	['MU', { label: 'Mauritius' }],
	['MX', { label: 'Mexico' }],
	['FM', { label: 'Micronesia' }],
	['MD', { label: 'Moldova' }],
	['MC', { label: 'Monaco' }],
	['MN', { label: 'Mongolia' }],
	['ME', { label: 'Montenegro' }],
	['MA', { label: 'Morocco' }],
	['MZ', { label: 'Mozambique' }],
	['NA', { label: 'Namibia' }],
	['NR', { label: 'Nauru' }],
	['NP', { label: 'Nepal' }],
	['NL', { label: 'Netherlands' }],
	['NZ', { label: 'New Zealand' }],
	['NI', { label: 'Nicaragua' }],
	['NE', { label: 'Niger' }],
	['NG', { label: 'Nigeria' }],
	['NO', { label: 'Norway' }],
	['OM', { label: 'Oman' }],
	['PK', { label: 'Pakistan' }],
	['PW', { label: 'Palau' }],
	['PS', { label: 'Palestine' }],
	['PA', { label: 'Panama' }],
	['PG', { label: 'Papua New Guinea' }],
	['PY', { label: 'Paraguay' }],
	['PE', { label: 'Peru' }],
	['PH', { label: 'Philippines' }],
	['PL', { label: 'Poland' }],
	['PT', { label: 'Portugal' }],
	['QA', { label: 'Qatar' }],
	['RO', { label: 'Romania' }],
	['RU', { label: 'Russia' }],
	['RW', { label: 'Rwanda' }],
	['KN', { label: 'Saint Kitts and Nevis' }],
	['LC', { label: 'Saint Lucia' }],
	['VC', { label: 'Saint Vincent and the Grenadines' }],
	['WS', { label: 'Samoa' }],
	['SM', { label: 'San Marino' }],
	['ST', { label: 'São Tomé and Príncipe' }],
	['SA', { label: 'Saudi Arabia' }],
	['SN', { label: 'Senegal' }],
	['RS', { label: 'Serbia' }],
	['SC', { label: 'Seychelles' }],
	['SL', { label: 'Sierra Leone' }],
	['SG', { label: 'Singapore' }],
	['SK', { label: 'Slovakia' }],
	['SI', { label: 'Slovenia' }],
	['SB', { label: 'Solomon Islands' }],
	['SO', { label: 'Somalia' }],
	['ZA', { label: 'South Africa' }],
	['SS', { label: 'South Sudan' }],
	['ES', { label: 'Spain' }],
	['LK', { label: 'Sri Lanka' }],
	['SD', { label: 'Sudan' }],
	['SR', { label: 'Suriname' }],
	['SZ', { label: 'Swaziland' }],
	['SE', { label: 'Sweden' }],
	['CH', { label: 'Switzerland' }],
	['SY', { label: 'Syria' }],
	['TJ', { label: 'Tajikistan' }],
	['TZ', { label: 'Tanzania' }],
	['TH', { label: 'Thailand' }],
	['TG', { label: 'Togo' }],
	['TO', { label: 'Tonga' }],
	['TT', { label: 'Trinidad and Tobago' }],
	['TN', { label: 'Tunisia' }],
	['TR', { label: 'Turkey' }],
	['TM', { label: 'Turkmenistan' }],
	['TV', { label: 'Tuvalu' }],
	['UG', { label: 'Uganda' }],
	['UA', { label: 'Ukraine' }],
	['AE', { label: 'United Arab Emirates' }],
	['GB', { label: 'United Kingdom' }],
	['US', { label: 'United States' }],
	['UY', { label: 'Uruguay' }],
	['UZ', { label: 'Uzbekistan' }],
	['VU', { label: 'Vanuatu' }],
	['VA', { label: 'Vatican City' }],
	['VE', { label: 'Venezuela' }],
	['VN', { label: 'Vietnam' }],
	['YE', { label: 'Yemen' }],
	['ZM', { label: 'Zambia' }],
	['ZW', { label: 'Zimbabwe' }]
];
