'use strict';

var Map              = require('es6-map')
  , memoize          = require('memoizee/lib/regular')
  , createEnum       = require('../../create-enum')
  , defineStringLine = require('../string-line')

  , members;

members = new Map([
	['AF', { label: 'Afghanistan'  }],
	['AL', { label: 'Albania'  }],
	['DZ', { label: 'Algeria'  }],
	['AS', { label: 'American Samoa'  }],
	['AD', { label: 'Andorra'  }],
	['AO', { label: 'Angola'  }],
	['AI', { label: 'Anguilla'  }],
	['AQ', { label: 'Antarctica'  }],
	['AG', { label: 'Antigua and Barbuda'  }],
	['AR', { label: 'Argentina'  }],
	['AM', { label: 'Armenia'  }],
	['AW', { label: 'Aruba'  }],
	['AU', { label: 'Australia'  }],
	['AT', { label: 'Austria'  }],
	['AZ', { label: 'Azerbaijan'  }],
	['BS', { label: 'Bahamas'  }],
	['BH', { label: 'Bahrain'  }],
	['BD', { label: 'Bangladesh'  }],
	['BB', { label: 'Barbados'  }],
	['BY', { label: 'Belarus'  }],
	['BE', { label: 'Belgium'  }],
	['BZ', { label: 'Belize'  }],
	['BJ', { label: 'Benin'  }],
	['BM', { label: 'Bermuda'  }],
	['BT', { label: 'Bhutan'  }],
	['BO', { label: 'Bolivia'  }],
	['BA', { label: 'Bosnia and Herzegovina'  }],
	['BW', { label: 'Botswana'  }],
	['BV', { label: 'Bouvet Island'  }],
	['BR', { label: 'Brazil'  }],
	['BQ', { label: 'British Antarctic Territory'  }],
	['IO', { label: 'British Indian Ocean Territory'  }],
	['VG', { label: 'British Virgin Islands'  }],
	['BN', { label: 'Brunei'  }],
	['BG', { label: 'Bulgaria'  }],
	['BF', { label: 'Burkina Faso'  }],
	['BI', { label: 'Burundi'  }],
	['KH', { label: 'Cambodia'  }],
	['CM', { label: 'Cameroon'  }],
	['CA', { label: 'Canada'  }],
	['CT', { label: 'Canton and Enderbury Islands'  }],
	['CV', { label: 'Cape Verde'  }],
	['KY', { label: 'Cayman Islands'  }],
	['CF', { label: 'Central African Republic'  }],
	['TD', { label: 'Chad'  }],
	['CL', { label: 'Chile'  }],
	['CN', { label: 'China'  }],
	['CX', { label: 'Christmas Island'  }],
	['CC', { label: 'Cocos [Keeling] Islands'  }],
	['CO', { label: 'Colombia'  }],
	['KM', { label: 'Comoros'  }],
	['CG', { label: 'Congo - Brazzaville'  }],
	['CD', { label: 'Congo - Kinshasa'  }],
	['CK', { label: 'Cook Islands'  }],
	['CR', { label: 'Costa Rica'  }],
	['HR', { label: 'Croatia'  }],
	['CU', { label: 'Cuba'  }],
	['CY', { label: 'Cyprus'  }],
	['CZ', { label: 'Czech Republic'  }],
	['CI', { label: 'Côte d’Ivoire'  }],
	['DK', { label: 'Denmark'  }],
	['DJ', { label: 'Djibouti'  }],
	['DM', { label: 'Dominica'  }],
	['DO', { label: 'Dominican Republic'  }],
	['NQ', { label: 'Dronning Maud Land'  }],
	['EC', { label: 'Ecuador'  }],
	['EG', { label: 'Egypt'  }],
	['SV', { label: 'El Salvador'  }],
	['GQ', { label: 'Equatorial Guinea'  }],
	['ER', { label: 'Eritrea'  }],
	['EE', { label: 'Estonia'  }],
	['ET', { label: 'Ethiopia'  }],
	['FK', { label: 'Falkland Islands'  }],
	['FO', { label: 'Faroe Islands'  }],
	['FJ', { label: 'Fiji'  }],
	['FI', { label: 'Finland'  }],
	['FR', { label: 'France'  }],
	['GF', { label: 'French Guiana'  }],
	['PF', { label: 'French Polynesia'  }],
	['TF', { label: 'French Southern Territories'  }],
	['FQ', { label: 'French Southern and Antarctic Territories'  }],
	['GA', { label: 'Gabon'  }],
	['GM', { label: 'Gambia'  }],
	['GE', { label: 'Georgia'  }],
	['DE', { label: 'Germany'  }],
	['GH', { label: 'Ghana'  }],
	['GI', { label: 'Gibraltar'  }],
	['GR', { label: 'Greece'  }],
	['GL', { label: 'Greenland'  }],
	['GD', { label: 'Grenada'  }],
	['GP', { label: 'Guadeloupe'  }],
	['GU', { label: 'Guam'  }],
	['GT', { label: 'Guatemala'  }],
	['GG', { label: 'Guernsey'  }],
	['GN', { label: 'Guinea'  }],
	['GW', { label: 'Guinea-Bissau'  }],
	['GY', { label: 'Guyana'  }],
	['HT', { label: 'Haiti'  }],
	['HM', { label: 'Heard Island and McDonald Islands'  }],
	['HN', { label: 'Honduras'  }],
	['HK', { label: 'Hong Kong SAR China'  }],
	['HU', { label: 'Hungary'  }],
	['IS', { label: 'Iceland'  }],
	['IN', { label: 'India'  }],
	['ID', { label: 'Indonesia'  }],
	['IR', { label: 'Iran'  }],
	['IQ', { label: 'Iraq'  }],
	['IE', { label: 'Ireland'  }],
	['IM', { label: 'Isle of Man'  }],
	['IL', { label: 'Israel'  }],
	['IT', { label: 'Italy'  }],
	['JM', { label: 'Jamaica'  }],
	['JP', { label: 'Japan'  }],
	['JE', { label: 'Jersey'  }],
	['JT', { label: 'Johnston Island'  }],
	['JO', { label: 'Jordan'  }],
	['KZ', { label: 'Kazakhstan'  }],
	['KE', { label: 'Kenya'  }],
	['KI', { label: 'Kiribati'  }],
	['KW', { label: 'Kuwait'  }],
	['KG', { label: 'Kyrgyzstan'  }],
	['LA', { label: 'Laos'  }],
	['LV', { label: 'Latvia'  }],
	['LB', { label: 'Lebanon'  }],
	['LS', { label: 'Lesotho'  }],
	['LR', { label: 'Liberia'  }],
	['LY', { label: 'Libya'  }],
	['LI', { label: 'Liechtenstein'  }],
	['LT', { label: 'Lithuania'  }],
	['LU', { label: 'Luxembourg'  }],
	['MO', { label: 'Macau SAR China'  }],
	['MK', { label: 'Macedonia'  }],
	['MG', { label: 'Madagascar'  }],
	['MW', { label: 'Malawi'  }],
	['MY', { label: 'Malaysia'  }],
	['MV', { label: 'Maldives'  }],
	['ML', { label: 'Mali'  }],
	['MT', { label: 'Malta'  }],
	['MH', { label: 'Marshall Islands'  }],
	['MQ', { label: 'Martinique'  }],
	['MR', { label: 'Mauritania'  }],
	['MU', { label: 'Mauritius'  }],
	['YT', { label: 'Mayotte'  }],
	['FX', { label: 'Metropolitan France'  }],
	['MX', { label: 'Mexico'  }],
	['FM', { label: 'Micronesia'  }],
	['MI', { label: 'Midway Islands'  }],
	['MD', { label: 'Moldova'  }],
	['MC', { label: 'Monaco'  }],
	['MN', { label: 'Mongolia'  }],
	['ME', { label: 'Montenegro'  }],
	['MS', { label: 'Montserrat'  }],
	['MA', { label: 'Morocco'  }],
	['MZ', { label: 'Mozambique'  }],
	['MM', { label: 'Myanmar [Burma]'  }],
	['NA', { label: 'Namibia'  }],
	['NR', { label: 'Nauru'  }],
	['NP', { label: 'Nepal'  }],
	['NL', { label: 'Netherlands'  }],
	['AN', { label: 'Netherlands Antilles'  }],
	['NT', { label: 'Neutral Zone'  }],
	['NC', { label: 'New Caledonia'  }],
	['NZ', { label: 'New Zealand'  }],
	['NI', { label: 'Nicaragua'  }],
	['NE', { label: 'Niger'  }],
	['NG', { label: 'Nigeria'  }],
	['NU', { label: 'Niue'  }],
	['NF', { label: 'Norfolk Island'  }],
	['KP', { label: 'North Korea'  }],
	['VD', { label: 'North Vietnam'  }],
	['MP', { label: 'Northern Mariana Islands'  }],
	['NO', { label: 'Norway'  }],
	['OM', { label: 'Oman'  }],
	['PC', { label: 'Pacific Islands Trust Territory'  }],
	['PK', { label: 'Pakistan'  }],
	['PW', { label: 'Palau'  }],
	['PS', { label: 'Palestinian Territories'  }],
	['PA', { label: 'Panama'  }],
	['PZ', { label: 'Panama Canal Zone'  }],
	['PG', { label: 'Papua New Guinea'  }],
	['PY', { label: 'Paraguay'  }],
	['YD', { label: 'People\'s Democratic Republic of Yemen'  }],
	['PE', { label: 'Peru'  }],
	['PH', { label: 'Philippines'  }],
	['PN', { label: 'Pitcairn Islands'  }],
	['PL', { label: 'Poland'  }],
	['PT', { label: 'Portugal'  }],
	['PR', { label: 'Puerto Rico'  }],
	['QA', { label: 'Qatar'  }],
	['RO', { label: 'Romania'  }],
	['RU', { label: 'Russia'  }],
	['RW', { label: 'Rwanda'  }],
	['RE', { label: 'Réunion'  }],
	['BL', { label: 'Saint Barthélemy'  }],
	['SH', { label: 'Saint Helena'  }],
	['KN', { label: 'Saint Kitts and Nevis'  }],
	['LC', { label: 'Saint Lucia'  }],
	['MF', { label: 'Saint Martin'  }],
	['PM', { label: 'Saint Pierre and Miquelon'  }],
	['VC', { label: 'Saint Vincent and the Grenadines'  }],
	['WS', { label: 'Samoa'  }],
	['SM', { label: 'San Marino'  }],
	['SA', { label: 'Saudi Arabia'  }],
	['SN', { label: 'Senegal'  }],
	['RS', { label: 'Serbia'  }],
	['CS', { label: 'Serbia and Montenegro'  }],
	['SC', { label: 'Seychelles'  }],
	['SL', { label: 'Sierra Leone'  }],
	['SG', { label: 'Singapore'  }],
	['SK', { label: 'Slovakia'  }],
	['SI', { label: 'Slovenia'  }],
	['SB', { label: 'Solomon Islands'  }],
	['SO', { label: 'Somalia'  }],
	['ZA', { label: 'South Africa'  }],
	['GS', { label: 'South Georgia and the South Sandwich Islands'  }],
	['KR', { label: 'South Korea'  }],
	['ES', { label: 'Spain'  }],
	['LK', { label: 'Sri Lanka'  }],
	['SD', { label: 'Sudan'  }],
	['SR', { label: 'Suriname'  }],
	['SJ', { label: 'Svalbard and Jan Mayen'  }],
	['SZ', { label: 'Swaziland'  }],
	['SE', { label: 'Sweden'  }],
	['CH', { label: 'Switzerland'  }],
	['SY', { label: 'Syria'  }],
	['ST', { label: 'São Tomé and Príncipe'  }],
	['TW', { label: 'Taiwan'  }],
	['TJ', { label: 'Tajikistan'  }],
	['TZ', { label: 'Tanzania'  }],
	['TH', { label: 'Thailand'  }],
	['TL', { label: 'Timor-Leste'  }],
	['TG', { label: 'Togo'  }],
	['TK', { label: 'Tokelau'  }],
	['TO', { label: 'Tonga'  }],
	['TT', { label: 'Trinidad and Tobago'  }],
	['TN', { label: 'Tunisia'  }],
	['TR', { label: 'Turkey'  }],
	['TM', { label: 'Turkmenistan'  }],
	['TC', { label: 'Turks and Caicos Islands'  }],
	['TV', { label: 'Tuvalu'  }],
	['UM', { label: 'U.S. Minor Outlying Islands'  }],
	['PU', { label: 'U.S. Miscellaneous Pacific Islands'  }],
	['VI', { label: 'U.S. Virgin Islands'  }],
	['UG', { label: 'Uganda'  }],
	['UA', { label: 'Ukraine'  }],
	['SU', { label: 'Union of Soviet Socialist Republics'  }],
	['AE', { label: 'United Arab Emirates'  }],
	['GB', { label: 'United Kingdom'  }],
	['US', { label: 'United States'  }],
	['ZZ', { label: 'Unknown or Invalid Region'  }],
	['UY', { label: 'Uruguay'  }],
	['UZ', { label: 'Uzbekistan'  }],
	['VU', { label: 'Vanuatu'  }],
	['VA', { label: 'Vatican City'  }],
	['VE', { label: 'Venezuela'  }],
	['VN', { label: 'Vietnam'  }],
	['WK', { label: 'Wake Island'  }],
	['WF', { label: 'Wallis and Futuna'  }],
	['EH', { label: 'Western Sahara'  }],
	['YE', { label: 'Yemen'  }],
	['ZM', { label: 'Zambia'  }],
	['ZW', { label: 'Zimbabwe'  }],
	['AX', { label: 'Åland Islands'  }]
]);

module.exports = memoize(function (db) {
	return defineStringLine(createEnum(db)).createEnum('Country', members);
});
